# Generated by Django 2.2 on 2020-09-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200911_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='type',
            field=models.CharField(choices=[('register', 'Регистрация'), ('password_reset', 'Восстановление пароля')], default='register', max_length=20, verbose_name='Тип токена'),
        ),
    ]
