# Generated by Django 2.2 on 2020-09-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200921_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='type',
            field=models.CharField(choices=[('password_reset', 'Восстановление пароля'), ('register', 'Регистрация')], default='register', max_length=20, verbose_name='Тип токена'),
        ),
    ]
